### ISSUE TITLE
Issue in landscape mode for iOS App

### ISSUE THREAD

**Issue by bwwhitt** [muxinc/examples#21]
When turning a device into landscape mode on a physical device, the display does not rotate accurately. You can see in the attached image where the camera view only covers half of the screen. While on simulation in XCode, it is displayed correctly. 

Device used is iPhone 11 running iOS 13.3.1. 

![IMG_3016](https://user-images.githubusercontent.com/24308003/74909605-4792a900-537e-11ea-91f0-50c76e8f735e.PNG)

**Comment by ruudkalis** [comment]
I am using this class too but I use storyboards instead of adding all views in code. What worked for me was to create a storyboard with a ViewController with `MuxBroadcastViewController` class then add a view called `_previewView` and connect to the class as an @IBOutlet like this:
`@IBOutlet weak var _previewView: UIView!`. 

Remove object lifecycle functions cause they will crash when you use storyboards.

Then in `viewDidLoad` you can uncomment the lines where previewView is added so it will look like this:
```
        //self._previewView = UIView(frame: self.view.bounds)
        if let previewView = self._previewView {
            self._muxLive.muxLiveDelegate = self
            self._muxLive.previewView = previewView
            //self.view.addSubview(previewView)
        }
```

This way the handling of orientation changes will be automatically solved by auto layout.

Alternatively implement something like this that updates the frame of the  `_previewView`:
```
override func willTransition(to newCollection: UITraitCollection, with coordinator: UIViewControllerTransitionCoordinator) {
    coordinator.animate(alongsideTransition: { context in
        if UIApplication.shared.statusBarOrientation.isLandscape {
            // activate landscape changes

        } else {
            // activate portrait changes
        }
    })
}
```

Hope you can work with any of these workaround hacks.

**Comment by gmakwana** [comment]
@dylanjha @ruudkalis @bwwhitt 
Any working solution on this issue?

It's starting stream in portrait and landscape mode perfectly but after starting stream if you change device orientation then it's not working.

**Comment by GeneticGenesis** [comment]
Hey @gmakwana, @ruudkalis, we just replaced this example with a more up-to-date example. This new version supports rotating correctly.

Let me know if you need any help with it!

Thanks!
