### ISSUE TITLE
Can we change stream quality after starting the stream?

### ISSUE THREAD

**Issue by gmakwana** [muxinc/examples#66]
We want to change the stream quality based on the speed of an internet in mobile device. Is it related to session preset in below mentioned code or change in bit rate?

Session preset change?
`rtmpStream.captureSettings = [
            .sessionPreset: AVCaptureSession.Preset.vga640x480,
            .continuousAutofocus: true,
            .continuousExposure: true,
            .fps: profile.frameRate
        ]`
        
Bit rate changein following methods?
`func rtmpStream(_ stream: RTMPStream, didPublishInsufficientBW connection: RTMPConnection) {}`
`func rtmpStream(_ stream: RTMPStream, didPublishSufficientBW connection: RTMPConnection) {}`

Which options will help us to increase or decrease the stream quality based on internet speed after we start the stream from mobile?

**Comment by aminamos** [comment]
Hi, we're going to answer this question through another support channel.

**Comment by aminamos** [comment]
@gmakwana adding a note to this issue for reference:

Because we already provide an adaptive bitrate with varying quality options for content served through Mux Video, all of Mux's encoding processes deliver an optimized bitrate ladder so you can avoid the ongoing manual process of fine tuning the resolution and bitrate used. https://mux.com/features/#smart-adaptive-bitrate-abr-ladder
﻿
﻿You'll also want to follow this guide of settings to specify on your encoder: https://docs.mux.com/guides/video/configure-broadcast-software#recommended-encoder-settings

**Comment by Nodalailama** [comment]
Hi,

@aminamos, so to be clear: the android/iphone app do not need to do adaptative bitrate when sending data to mux server because Mux already do it on the server side, am I right ?

But, if I understand why adaptative bitrate on the application side is a "recommended" is that the user do not have always a constant stable internet connexion and it can drop some frame with not good result at the end.

Thus, what I am understanding is that the way Mux process the incoming stream imply a fixed bitrate on the android/iphone app side, could you confirm me that ?

That's very much.

PS: ideally, Mux was saying in a blog post that it will allow to use SRT transport protocol seem to be better than rtmp, could you also give me feedback on that ?

**Comment by philcluff** [comment]
Hey @Nodalailama, 

Yes, this is correct, Mux will always create a set of renditions on the server side, even if the input isn't adaptive bitrate. 

We strongly recommend also having some form of adaptive bitrate on the encoder (in this case your input application).

SRT is on our roadmap, but I don't have a confirmed date right now. 

Thanks.

**Comment by Nodalailama** [comment]
Ok, thanks for the answers.
